from .metals_requests import get_all_metals
from .metals_requests import get_single_metal
from .sizes_requests import get_all_sizes
from .sizes_requests import get_single_size
from .styles_requests import get_all_styles
from .styles_requests import get_single_style
from .client_orders import get_all_orders
from .client_orders import get_single_order
from .client_orders import create_order
from .client_orders import delete_order
from .client_orders import update_order